# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='subscribe',
            field=models.IntegerField(blank=True, null=True, verbose_name='Подписан'),
        ),
    ]
