# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogposts_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='subscribe',
            field=models.CharField(max_length=30, null=True, verbose_name='Подписан'),
        ),
    ]
